# Generated by Django 6.0.1 on 2026-01-23 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movimentacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                ("id_insumo", models.AutoField(primary_key=True, serialize=False)),
                ("item_insumo", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movimentacao",
                    models.ForeignKey(
                        db_column="id_movimentacao",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="movimentacao.movimentacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo",
                "verbose_name_plural": "Insumos",
                "db_table": "insumos",
            },
        ),
    ]
