STATUS_MOVIMENTACAO = [
    "ABERTA",
    "EM_TRIAGEM",
    "EM_DIAGNOSTICO",
    "AGUARDANDO_PECA",
    "EM_MANUTENCAO",
    "EM_INSPECAO",
    "FINALIZADA",
]

STATUS_MANUTENCAO = [
    "EM_MANUTENCAO",
    "EM_INSPECAO",
    "AGUARDANDO_PECA",
]
