# Generated by Django 6.0.1 on 2026-01-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("veiculo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pa",
                    models.CharField(max_length=20, verbose_name="Posto de Apoio (PA)"),
                ),
                (
                    "os_numero",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número da OS"
                    ),
                ),
                (
                    "inicio_problema",
                    models.DateTimeField(verbose_name="Início do Problema"),
                ),
                (
                    "conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Conclusão"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        db_column="prefixo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_servico",
                        to="veiculo.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "db_table": "os",
                "indexes": [models.Index(fields=["veiculo"], name="fk_os_veiculo")],
            },
        ),
    ]
