# Generated by Django 6.0.1 on 2026-01-22 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("os", "0001_initial"),
        ("veiculo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordemservico",
            name="os_numero",
            field=models.CharField(max_length=20, verbose_name="Número da OS"),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="veiculo",
            field=models.ForeignKey(
                db_column="prefixo_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordens_servico",
                to="veiculo.veiculo",
            ),
        ),
    ]
