# Generated by Django 6.0.1 on 2026-01-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaborador", "0001_initial"),
        ("os", "0002_alter_ordemservico_os_numero_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id_movimentacao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="Data e Hora da Movimentação"),
                ),
                ("status", models.CharField(max_length=30, verbose_name="Status")),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "os",
                    models.ForeignKey(
                        db_column="id_os",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="os.ordemservico",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        db_column="responsavel_matricula",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="colaborador.colaborador",
                        to_field="matricula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "db_table": "movimentacao",
                "indexes": [
                    models.Index(fields=["os"], name="fk_mov_os"),
                    models.Index(fields=["responsavel"], name="fk_mov_colaborador"),
                    models.Index(
                        fields=["status"], name="movimentaca_status_d44c78_idx"
                    ),
                    models.Index(
                        fields=["data_hora"], name="movimentaca_data_ho_e7c20d_idx"
                    ),
                ],
            },
        ),
    ]
