# Generated by Django 6.0.1 on 2026-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Celular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=15, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                ("fabricante", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "garagem_atual",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "codigo_imei",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("apelido", models.CharField(max_length=15, unique=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "celular",
                "indexes": [
                    models.Index(
                        fields=["data_criacao"], name="celular_data_cr_1bd7b2_idx"
                    ),
                    models.Index(
                        fields=["garagem_atual"], name="celular_garagem_811ef2_idx"
                    ),
                ],
            },
        ),
    ]
