# Generated by Django 6.0.1 on 2026-01-08 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cooperativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "cooperativa",
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixo", models.CharField(max_length=10, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Basculante", "Basculante"),
                            ("Selectolix", "Selectolix"),
                            ("Baú", "Baú"),
                            ("Pá Carregadeira", "Pá Carregadeira"),
                            ("Retroescavadeira", "Retroescavadeira"),
                            ("Compactador", "Compactador"),
                            ("Varredeira", "Varredeira"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "placa_veiculo",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Placa do Veículo",
                    ),
                ),
                (
                    "em_manutencao",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="NÃO",
                        max_length=3,
                        verbose_name="Em Manutenção",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Seletiva", "Seletiva"),
                            ("Domiciliar", "Domiciliar"),
                            ("Remoção", "Remoção"),
                            ("Varrição", "Varrição"),
                        ],
                        default="Seletiva",
                        max_length=11,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Não", "Não")],
                        default="Não",
                        max_length=3,
                        verbose_name="Equipamento",
                    ),
                ),
            ],
            options={
                "db_table": "veiculo",
            },
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("matricula", models.IntegerField(unique=True)),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("MOTORISTA", "MOTORISTA"),
                            ("OPERADOR", "OPERADOR"),
                            ("COLETOR", "COLETOR"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("DIURNO", "DIURNO"),
                            ("NOTURNO", "NOTURNO"),
                            ("VESPERTINO", "VESPERTINO"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "ATIVO"), ("INATIVO", "INATIVO")],
                        max_length=7,
                    ),
                ),
                (
                    "pa",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
            options={
                "db_table": "colaborador",
                "indexes": [
                    models.Index(fields=["nome"], name="colaborador_nome_ab3ec6_idx"),
                    models.Index(
                        fields=["matricula"], name="colaborador_matricu_23ec80_idx"
                    ),
                    models.Index(
                        fields=["funcao"], name="colaborador_funcao_6740bc_idx"
                    ),
                    models.Index(fields=["pa"], name="colaborador_pa_ac17c9_idx"),
                    models.Index(fields=["turno"], name="colaborador_turno_2f788b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Pesagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                (
                    "responsavel_coop",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hora_chegada", models.TimeField()),
                ("hora_saida", models.TimeField()),
                ("numero_doc", models.CharField(max_length=9, unique=True)),
                ("volume_carga", models.CharField(max_length=10)),
                (
                    "tipo_pesagem",
                    models.CharField(
                        choices=[
                            ("SELETIVA", "Seletiva"),
                            ("CATA-TRECO", "Cata-treco"),
                        ],
                        default="SELETIVA",
                        max_length=20,
                    ),
                ),
                (
                    "peso_calculado",
                    models.DecimalField(
                        decimal_places=3, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "garagem",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                            ("SEM GARAGEM", "Sem Garagem"),
                        ],
                        default="SEM GARAGEM",
                        max_length=12,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Diurno", "Diurno"),
                            ("Noturno", "Noturno"),
                            ("SEM TURNO", "SEM TURNO"),
                        ],
                        default="SEM TURNO",
                        max_length=10,
                    ),
                ),
                (
                    "colaborador_id",
                    models.ManyToManyField(
                        related_name="pesagens_coletores", to="pesagem.colaborador"
                    ),
                ),
                (
                    "cooperativa_id",
                    models.ForeignKey(
                        db_column="cooperativa_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pesagem.cooperativa",
                    ),
                ),
                (
                    "motorista_id",
                    models.ForeignKey(
                        db_column="motorista_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesagens_motorista",
                        to="pesagem.colaborador",
                    ),
                ),
                (
                    "prefixo_id",
                    models.ForeignKey(
                        db_column="prefixo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pesagem.veiculo",
                    ),
                ),
            ],
            options={
                "db_table": "pesagem",
                "indexes": [
                    models.Index(fields=["data"], name="pesagem_data_535a29_idx"),
                    models.Index(
                        fields=["numero_doc"], name="pesagem_numero__ff910d_idx"
                    ),
                    models.Index(
                        fields=["prefixo_id"], name="pesagem_prefixo_5b2a58_idx"
                    ),
                    models.Index(
                        fields=["motorista_id"], name="pesagem_motoris_1cae36_idx"
                    ),
                    models.Index(
                        fields=["cooperativa_id"], name="pesagem_coopera_36cb68_idx"
                    ),
                    models.Index(
                        fields=["volume_carga"], name="pesagem_volume__c4b9d9_idx"
                    ),
                    models.Index(
                        fields=["peso_calculado"], name="pesagem_peso_ca_117105_idx"
                    ),
                    models.Index(
                        fields=["hora_chegada"], name="pesagem_hora_ch_08ddf0_idx"
                    ),
                    models.Index(
                        fields=["hora_saida"], name="pesagem_hora_sa_800e9c_idx"
                    ),
                    models.Index(
                        fields=["responsavel_coop"], name="pesagem_respons_2c4ae5_idx"
                    ),
                    models.Index(fields=["garagem"], name="pesagem_garagem_f071d7_idx"),
                    models.Index(fields=["turno"], name="pesagem_turno_91a047_idx"),
                    models.Index(
                        fields=["tipo_pesagem"], name="pesagem_tipo_pe_50c5f7_idx"
                    ),
                ],
            },
        ),
    ]
