# Generated by Django 6.0.1 on 2026-01-14 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colaborador", "0001_initial"),
        ("cooperativa", "0001_initial"),
        ("veiculo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaBatida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_toneladas", models.FloatField(default=2601.0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pesagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                (
                    "responsavel_coop",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hora_chegada", models.TimeField()),
                ("hora_saida", models.TimeField()),
                ("numero_doc", models.CharField(max_length=9, unique=True)),
                ("volume_carga", models.CharField(max_length=10)),
                (
                    "tipo_pesagem",
                    models.CharField(
                        choices=[
                            ("SELETIVA", "Seletiva"),
                            ("CATA-TRECO", "Cata-treco"),
                        ],
                        default="SELETIVA",
                        max_length=20,
                    ),
                ),
                (
                    "peso_calculado",
                    models.DecimalField(
                        decimal_places=3, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "garagem",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                            ("SEM GARAGEM", "Sem Garagem"),
                        ],
                        default="SEM GARAGEM",
                        max_length=12,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Diurno", "Diurno"),
                            ("Noturno", "Noturno"),
                            ("SEM TURNO", "SEM TURNO"),
                        ],
                        default="SEM TURNO",
                        max_length=10,
                    ),
                ),
                (
                    "colaboradores",
                    models.ManyToManyField(
                        related_name="pesagens_coletor", to="colaborador.colaborador"
                    ),
                ),
                (
                    "cooperativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesagens",
                        to="cooperativa.cooperativa",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        db_column="motorista_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesagens_motorista",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "prefixo",
                    models.ForeignKey(
                        db_column="prefixo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pesagens",
                        to="veiculo.veiculo",
                    ),
                ),
            ],
            options={
                "db_table": "pesagem",
                "indexes": [
                    models.Index(fields=["data"], name="pesagem_data_535a29_idx"),
                    models.Index(
                        fields=["numero_doc"], name="pesagem_numero__ff910d_idx"
                    ),
                    models.Index(fields=["prefixo"], name="pesagem_prefixo_5b2a58_idx"),
                    models.Index(
                        fields=["motorista"], name="pesagem_motoris_1cae36_idx"
                    ),
                    models.Index(
                        fields=["cooperativa"], name="pesagem_coopera_36cb68_idx"
                    ),
                    models.Index(
                        fields=["volume_carga"], name="pesagem_volume__c4b9d9_idx"
                    ),
                    models.Index(
                        fields=["peso_calculado"], name="pesagem_peso_ca_117105_idx"
                    ),
                    models.Index(
                        fields=["hora_chegada"], name="pesagem_hora_ch_08ddf0_idx"
                    ),
                    models.Index(
                        fields=["hora_saida"], name="pesagem_hora_sa_800e9c_idx"
                    ),
                    models.Index(
                        fields=["responsavel_coop"], name="pesagem_respons_2c4ae5_idx"
                    ),
                    models.Index(fields=["garagem"], name="pesagem_garagem_f071d7_idx"),
                    models.Index(fields=["turno"], name="pesagem_turno_91a047_idx"),
                    models.Index(
                        fields=["tipo_pesagem"], name="pesagem_tipo_pe_50c5f7_idx"
                    ),
                ],
            },
        ),
    ]
