# Generated by Django 6.0.1 on 2026-01-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pesagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaBatida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_toneladas", models.FloatField(default=2601.0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
