# Generated by Django 6.0.1 on 2026-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixo", models.CharField(max_length=10, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Basculante", "Basculante"),
                            ("Selectolix", "Selectolix"),
                            ("Baú", "Baú"),
                            ("Pá Carregadeira", "Pá Carregadeira"),
                            ("Retroescavadeira", "Retroescavadeira"),
                            ("Compactador", "Compactador"),
                            ("Varredeira", "Varredeira"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "placa_veiculo",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Placa do Veículo",
                    ),
                ),
                (
                    "em_manutencao",
                    models.CharField(
                        choices=[("SIM", "Sim"), ("NÃO", "Não")],
                        default="NÃO",
                        max_length=3,
                        verbose_name="Em Manutenção",
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Seletiva", "Seletiva"),
                            ("Domiciliar", "Domiciliar"),
                            ("Remoção", "Remoção"),
                            ("Varrição", "Varrição"),
                        ],
                        default="Seletiva",
                        max_length=11,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                (
                    "equipamento",
                    models.CharField(
                        choices=[("Sim", "Sim"), ("Não", "Não")],
                        default="Não",
                        max_length=3,
                        verbose_name="Equipamento",
                    ),
                ),
            ],
            options={
                "db_table": "veiculo",
            },
        ),
    ]
