# Generated by Django 6.0.1 on 2026-01-28 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("celular", "0001_initial"),
        ("colaborador", "0001_initial"),
        ("veiculo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pa",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                        ],
                        max_length=10,
                    ),
                ),
                ("rota", models.CharField(max_length=10)),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Seletiva", "Seletiva"),
                            ("Domiciliar", "Domiciliar"),
                            ("Varrição", "Varrição"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "rota",
                "unique_together": {("pa", "rota", "tipo_servico")},
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_setor", models.CharField(max_length=100, unique=True)),
                ("regiao", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "setor",
                "indexes": [
                    models.Index(
                        fields=["nome_setor"], name="setor_nome_se_1ebf32_idx"
                    ),
                    models.Index(fields=["regiao"], name="setor_regiao_5b5bed_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Soltura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_entrega_chave", models.TimeField()),
                ("hora_saida_frota", models.TimeField()),
                ("data_soltura", models.DateField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True, null=True)),
                ("hora_retorno_frota", models.DateTimeField(blank=True, null=True)),
                ("data_referencia", models.DateField(blank=True, null=True)),
                (
                    "garagem",
                    models.CharField(
                        choices=[
                            ("PA1", "PA1"),
                            ("PA2", "PA2"),
                            ("PA3", "PA3"),
                            ("PA4", "PA4"),
                        ],
                        default="PA1",
                        max_length=10,
                    ),
                ),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("lider", models.CharField(max_length=55)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Em Andamento", "Em Andamento"),
                            ("Concluído", "Concluído"),
                        ],
                        default="Em Andamento",
                        max_length=14,
                    ),
                ),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Seletiva", "Seletiva"),
                            ("Domiciliar", "Domiciliar"),
                            ("Remoção", "Remoção"),
                            ("Varrição", "Varrição"),
                        ],
                        default="Seletiva",
                        max_length=10,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("Diurno", "Diurno"),
                            ("Noturno", "Noturno"),
                            ("Matutino", "Matutino"),
                            ("Vespertino", "Vespertino"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "celular_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solturas",
                        to="celular.celular",
                    ),
                ),
                (
                    "coletores",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"funcao": "Coletor", "status": "ATIVO"},
                        related_name="solturas_coletor",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        limit_choices_to={
                            "funcao__in": ["Motorista", "Operador"],
                            "status": "ATIVO",
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solturas_motorista",
                        to="colaborador.colaborador",
                    ),
                ),
                (
                    "rota",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solturas",
                        to="soltura.rota",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solturas_setor",
                        to="soltura.setor",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        limit_choices_to={"em_manutencao": "NÃO"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solturas",
                        to="veiculo.veiculo",
                    ),
                ),
            ],
            options={
                "db_table": "soltura",
            },
        ),
    ]
