# Generated by Django 6.0.1 on 2026-01-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfirmacaoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_doc",
                    models.CharField(db_index=True, max_length=14, unique=True),
                ),
                (
                    "nome_vistoriador",
                    models.CharField(db_index=True, default="USER", max_length=20),
                ),
                ("data_servico", models.DateField(db_index=True)),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Remoção", "Remoção"),
                            ("Seletiva", "Seletiva"),
                            ("Domiciliar", "Domiciliar"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
            ],
            options={
                "db_table": "confirmacao_servico",
            },
        ),
        migrations.CreateModel(
            name="ImagemConfirmacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.URLField(max_length=600)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "confirmacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="confirmacao.confirmacaoservico",
                    ),
                ),
            ],
        ),
    ]
